### ISSUE TITLE
code/main.cpp: Запуск успешный, но не работает.

### ISSUE THREAD

**Issue by 7azhigin** [rus-school-pack/points-manager#3]
Некоректно работает:
```
Введите свои оценки(0 для конца ввода):
222
0
Введите желаемую оценку:
3
Средняя оценка: 222
Нужно оценок для цели: 0x222баллов
```
Возможно это из за того что я на линуксе, но прочитав код (я закоментировал локализацию)  @ничего что могло помешать - не нашёл.

**Comment by Slavlen** [comment]
Нужно водить так:
4
5
4
0

пн, 14 сент. 2020 г. в 22:46, Bogdan <notifications@github.com>:

**Comment by Slavlen** [comment]
Пока топорно, позже исправлю на ввод строкой...

пн, 14 сент. 2020 г. в 22:57, Вячеслав Дружинин <slavlen2001@gmail.com>:

**Comment by b7azhigin** [comment]
> Пока топорно, позже исправлю на ввод строкой...
Может попробовать вводить не как число, а как char'ы, а птотом переводить в short int?

**Comment by Slavlen** [comment]
Я знаю, как правильно сделать, но быстрым вариантом воспользовался.

пн, 14 сент. 2020 г., 23:53 Bogdan <notifications@github.com>:

**Comment by 7azhigin** [comment]
Ok.
